### ISSUE TITLE
Estratégia de testes

### ISSUE THREAD

**Issue by feromes** [geoinfo-smdu/geosampa-e2e#1]
@yubathom acho que podemos começar com testando uma característica do Geosampa relatada no último treinamento. Uma usuária reclamou que a pesquisa de endereço, clicando na lupa e depois na aba endereço não permite casos em que o logradouro tenha mais do que 30 caracteres, como no caso do endereço: Av. Antonio Carlos Benjamin dos Santos

![pesquisa de endereco geosampa](https://user-images.githubusercontent.com/31536/65918271-a47dca80-e3af-11e9-8fa2-1541a6a24de1.PNG)
.

**Comment by yubathom** [comment]
Perfeito. Vou escrever este teste amanhã. Por enquanto apenas para a versão pública (geosampa.prefeitura). Depois adaptamos para a versão interna (mapas.geosampa)

**Comment by yubathom** [comment]
![ezgif-1-9ca10c00b46d](https://user-images.githubusercontent.com/4117768/65992896-80c98b80-e466-11e9-8566-2ebb77bb5222.gif)
